---
- name: install pre-req packages
  yum:
    name: "{{ nagios_pre_req_packages }}"
    state: present
- name: adding nagios user group
  group:
    name: nagcmd
    state: present
- name: Add the user 'nagios' with a group of 'nagcmd'
  user:
    name: nagios
    comment: Nagios User
    group: nagcmd
- name: Add the user 'apache' appending the group 'nagcmd'
  user:
    name: james
    group: nagcmd
    append: yes
- name: Copying the nagios zip file
  copy:
    src: "nagios.zip"
    dest: "/root/nagios.zip"

- name: using unarchive module to Unzip
  unarchive:
    src: /root/nagios.zip
    dest: /root
    remote_src: no

- name: executing the configure command in the nagios directory
  command:
    cmd: "./configure --with-command-group=nagcmd"
    chdir: "/root/nagios-4.4.2"

- name: making all files in the directory
  command:
    cmd: make
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make all
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make install
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make install-init
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make install-commandmode
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make install-config
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  command:
    cmd: make install-webconf
    chdir: /root/nagios-4.4.2

- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: 'nagiosadmin'
    create: yes
    crypt_scheme: ldap_sha1

- name: Copying the nagios-plugins zip file
  copy:
    src: "nagios-plugins.zip"
    dest: "/root/nagios-plugins.zip"

- name: using unarchive module to Unzip
  unarchive:
    src: /root/nagios-plugins.zip
    dest: /root
    remote_src: no

- name: executing the configure command in the nagios directory
  command:
    cmd: "./configure"
    chdir: "/root/nagios-plugins"

- name: making all files in the directory
  command:
    cmd: make
    chdir: /root/nagios-plugins

- name: making all files in the directory
  command:
    cmd: make install
    chdir: /root/nagios-plugins

- name: restarting service http
  service:
    name: httpd
    state: reloaded

- name: installing nagios plugins
  yum:
    name: nagios-plugins
    state: present
    disablerepo: "*"
    enablerepo: nagios_ansible

- name: Enable service nagios and ensure it is not masked
  systemd:
    name: nagios
    enabled: yes
    state: started
