---
- name: install pre-req packages
  yum:
    name: "{{ nagios_pre_req_packages }}"
    state: present
- name: adding nagios user group
  group:
    name: nagcmd
    state: present
- name: Add the user 'nagios' with a group of 'nagcmd'
  user:
    name: nagios
    comment: Nagios User
    group: nagcmd
- name: Add the user 'apache' appending the group 'nagcmd'
  user:
    name: james
    group: nagcmd
    append: yes
- name: Copying the nagios zip file
  copy:
    src: "nagios.zip"
    dest: "/root/nagios.zip"

- name: using unarchive module to Unzip
  unarchive:
    src: /root/nagios.zip
    dest: /root
    remote_src: no

- name: executing the configure command in the nagios directory
  shell: "configure --with-command-group=nagcmd"
  args:
    chdir: /root/nagios-4.4.2

- name: making all files in the directory
  shell: "make && make all && make install && make install-init && make install-commandmode && make install-config && make install-webconf"
  args:
    chdir: /root/nagios-4.4.2
# - name: Add a user to a password file and ensure permissions are set
#   community.general.htpasswd:
#     path: /usr/local/nagios/etc/htpasswd.users
#     name: nagiosadmin
#     password: 'nagiosadmin'
#     create: yes
#     crypt_scheme: ldap_sha1

# - name: restarting service http
#   service:
#     name: httpd
#     state: reloaded

# - name: Enable service nagios and ensure it is not masked
#   systemd:
#     name: httpd
#     enabled: yes
#     state: started
