---
- name: Nagios
  hosts: masters
  gather_facts: no
  tasks:
    - name: Update
      yum:
        name: "*"
        state: latest
      tags:
        - update

    - name: Install
      yum:
        name: nagios
        state: latest
      tags:
        - install

    - htpasswd:
        path: /etc/nagios/passwd
        name: nagiosadmin
        password: seamless
        crypt_scheme: md5_crypt
      tags:
        - htpass

    - service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nagios
        - httpd
      tags:
        - service
