---
- name: setting up nagios, httpd and repository using roles.
  hosts: masters
  roles:
    - role: pre-nagios
      become: true
      tags:
        - setup
        - pre-requisite
    - role: nagios
      become: true
      tags:
        - nagios
        - nagios_master
      