---
- name: setting up nagios, httpd and repository using roles.
  hosts: masters
  roles:
    - role: pre-nagios
      become: true
      tags:
        - setup
        - pre-requisite

    - role: master
      become: true
      tags:
        - nagios
        - nagios_master

    - role: child_master
      become: true
      tags:
        - child_master
- name: setup on child_nodes
  hosts: childs
  roles:
    - role: childs
      become: true
      tags:
        - nagios_childs
