---
-  name: Creating repo folder
   file:
      path: /var/www/html/nagios_ansible
      state: directory
-   name: Copying the pre-requisite packages
    copy:
      src: "{{ packages }}"
      dest: "/var/www/html/nagios_ansible/."
    with_items:

-   name: using shell module to Un-taring
    shell: tar -xvf /var/www/html/nagios_ansible/{{ packages }}

