---
- name: Creating repo folder
  file:
    path: /var/www/html/nagios_ansible
    state: directory
- name: Copying the pre-requisite packages
  copy:
    src: "rpms.zip"
    dest: "/var/www/html/nagios_ansible/rpms.zip" 

- name: using shell module to Un-tarin
  unarchive: 
    src: /var/www/html/nagios_ansible/rpms.zip 
    dest: /var/www/html/nagios_ansible/
    remote_src: no
- name: Add repository with file protocol
  yum_repository:
    name: nagios_ansible
    description: Nagios 
    baseurl: file:////var/www/html/nagios_ansible/
    
- name: install httpd
  yum:
    name: httpd
    state: present
    disablerepo: "*"
    enablerepo: nagios_ansible
- name: changing port 80 to 8008
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: "^Listen 80$"
    line: "Listen 8008"
- name: restarting service http 
  service:
    name: httpd
    state: reloaded
# - name: Add repository with file protocol
#   yum_repository:
#     name: nagios_ansible
#     description: Nagios
#     state: absent
#     baseurl: file:////var/www/html/nagios_ansible/
- name: Add repository with http protocol
  yum_repository:
    name: nagios_ansible
    description: Nagios through ansible
    state: present
    baseurl: http://{{master_ip}}:8008/nagios_ansible
