---
- name: Creating repo folder
  file:
    path: /var/www/html/nagios_ansible
    state: directory

- name: Copying the pre-requisite packages
  copy:
    src: "rpms.zip"
    dest: "/var/www/html/nagios_ansible/rpms.zip"

- name: install unzip
  yum:
    name: unzip
    state: present

- name: install createrepo
  yum:
    name: createrepo
    state: present

- name: using unarchive module to Un-tarin
  unarchive:
    src: /var/www/html/nagios_ansible/rpms.zip
    dest: /var/www/html/nagios_ansible/
    remote_src: no

- name: creating a repo on html path
  shell:
    cmd:  "createrepo nagios_ansible"
    chdir: /var/www/html

- name: Add nagios repository with local file protocol
  yum_repository:
    name: nagios_ansible
    description: Nagios
    baseurl: file:///var/www/html/nagios_ansible/

- name: install httpd
  yum:
    name: httpd
    state: present
    disablerepo: "*"
    enablerepo: nagios_ansible

- name: install python2-passlib
  yum:
    name: python2-passlib
    state: present
    disablerepo: "*"
    enablerepo: nagios_ansible

- name: changing port 80 to Custom
  lineinfile:
    path: "/etc/httpd/conf/httpd.conf"
    regexp: "^Listen 80$"
    line: "Listen {{ http_custom_port }}"

- name: restarting service http
  service:
    name: httpd
    state: reloaded

- name: Add nagios repository with html path protocol
  yum_repository:
    name: nagios_ansible
    description: Nagios through ansible
    state: present
    baseurl: http://{{master_ip}}:{{ http_custom_port }}/nagios_ansible
    gpgcheck: no
