---
-  name: Creating repo folder
   file:
      path: /var/www/html/nagios_ansible
      state: directory
-   name: Copying the pre-requisite packages
    copy:
      src: "{{ item }}"
      dest: "/var/www/html/nagios_ansible/{{ item }}"
    with_items:
      - nagios.gz
      - nrpe.tar.gz
      - pre-install.tgz
-   name: using shell module to Un-taring
    shell: tar -xvf /var/www/html/nagios_ansible/{{ item }} -C /var/www/html/nagios_ansible/
    with_items:
      - nagios.gz
      - nrpe.tar.gz
      - pre-install.tgz
