---
-  name: Creating repo folder
   file:
      path: /var/www/html/nagios_ansible
      state: directory
-   name: Un-taring all the pre-requisite packages
    unarchive:
      src: ../files/pre-install.tgz
      dest: /var/www/html/nagios_ansible/.
      remote_src: true
    delegate_to: 127.0.0.1