---
- name: conf.d directory in master node.
  file: 
    path: /etc/nagios/conf.d
    state: directory
    group: nagios
    owner: nagios
    mode: "0755"

- name: include conf.d in nagios.cfg
  lineinfile:
    path: /etc/nagios/nagios.cfg
    line: "cfg_dir=/etc/nagios/conf.d"

- name: host file in conf.d directory
  file:
    path: /etc/nagios/conf.d/hosts.cfg
    state: touch

- name: adding every child host entry in hosts.cfg file
  blockinfile:
    path: /etc/nagios/conf.d/hosts.cfg
    block: |
      define host {
          use             linux-server
          host_name       {{ item.name }}
          alias           {{ item.name }}
          address         {{ item.ip }}
        }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items: "{{ childs }}"


- name: hostgroups file in conf.d directory
  file:
    path: /etc/nagios/conf.d/hostgroups.cfg
    state: touch

- name: adding child hostgroup in hostgroups.cfg file
  blockinfile:
    path: /etc/nagios/conf.d/hostgroups.cfg
    block: |
      define hostgroup{
        hostgroup_name  child_nodes
        alias           {{ host_group_alias }}
        members         {{ host_group }}
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  

- name: services file in conf.d directory
  file:
    path: /etc/nagios/conf.d/services.cfg
    state: touch

- name: adding every child host entry in services.cfg file
  blockinfile:
    path: /etc/nagios/conf.d/services.cfg
    block: |
      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     PING
        check_command           check_ping!100.0,20%!500.0,60%
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     Root Partition
        check_command           check_local_disk!20%!10%!/
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     Current Users
        check_command           check_local_users!20!50
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     Total Processes
        check_command           check_local_procs!250!400!RSZDT
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     Current Load
        check_command           check_local_load!5.0,4.0,3.0!10.0,6.0,4.0
      }

      define service {
        use                     local-service
        hostgroup_name     		child_nodes
        service_description     Swap Usage
        check_command           check_local_swap!20%!10%
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     SSH
        check_command           check_ssh
        notifications_enabled   0
      }

      define service {
        use                     local-service
        hostgroup_name          child_nodes
        service_description     HTTP
        check_command           check_http
        notifications_enabled   0
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  
