---
user:

master_ip: 127.0.0.1      # IP for nagios master

nagios_pkg_dir: nagios-4.4.2       # Nagios source directory
nagios_plugions_pkg_dir: nagios-plugins    # Nagios plugins source directory
http_custom_port: 8008

childs:
  - 
    name: child1
    ip: 127.0.0.1
  - 
    name: client
    ip: 192.168.1.244

host_group: 
  - child1, client
host_group_alias: 
  - "child nodes"
host_group_name: 
  - prod_child