---
user:

master_ip: 192.168.1.243    # IP for nagios master

nagios_pkg_dir: nagios-4.4.2       # Nagios source directory
nagios_plugions_pkg_dir: nagios-plugins    # Nagios plugins source directory
http_custom_port: 8008

childs:
  - 
    name: client1
    ip: 192.168.1.97
  - 
    name: client2
    ip: 192.168.1.244
  - 
    name: client3
    ip: 192.168.1.98


host_group: "client1,client2,client3"
host_group_alias: "child nodes"
host_group_name: "prod_child"