---
- name: Nagios - Prerequisite
  yum:
    name: "{{ packages }}"
    state: present
  vars:
      packages:
        - httpd-tools
        - php
        - gcc
        - glibc
        - glibc-common
        - gd
        - gd-devel
        - make
        - net-snmp

- name: Nagios - Add Group
  group:
    name: nagcmd
    state: present

- name: Nagios - Add User 'nagios' as Group Member Of 'nagcmd'
  user:
    name: nagios
    group: nagcmd

- name: Nagios - Add User 'apache' as Group Member Of 'nagcmd'
  user:
    name: apache
    group: nagcmd
    append: yes

- name: Nagios - Copy Source Zip
  copy:
    src: "nagios.zip"
    dest: "~/nagios.zip"

- name: Nagios - Unzip
  unarchive:
    src: ~/nagios.zip
    dest: ~/{{ nagios_pkg_dir }}
    remote_src: no

- name: Nagios - Configure Source Directory
  command:
    cmd: "./configure --with-command-group=nagcmd"
    chdir: "~/{{ nagios_pkg_dir }}"

- name: Nagios - Make
  command:
    cmd: make
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Make All
  command:
    cmd: make all
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Make Install
  command:
    cmd: make install
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Install-Init
  command:
    cmd: make install-init
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Command Mode
  command:
    cmd: make install-commandmode
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Config
  command:
    cmd: make install-config
    chdir: ~/{{ nagios_pkg_dir }}

- name: Nagios - Web Conf
  command:
    cmd: make install-webconf
    chdir: ~/{{ nagios_pkg_dir }}

- name: Password File For 'nagios' User
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: 'nagiosadmin'
    create: yes
    crypt_scheme: ldap_sha1

- name: NRPE - Install
  yum:
    name: nrpe
    state: present

- name: NagiosPlugins - Copy Source Zip
  copy:
    src: "{{ nagios_plugions_pkg_dir }}.zip"
    dest: "~/{{ nagios_plugions_pkg_dir }}.zip"

- name: NagiosPlugins - Unzip
  unarchive:
    src: ~/{{ nagios_plugions_pkg_dir }}.zip
    dest: ~/
    remote_src: no

- name: NagiosPlugins - Configure Source Directory
  command:
    cmd: "./configure"
    chdir: "~/{{ nagios_plugions_pkg_dir }}"

- name: NagiosPlugins - Make
  command:
    cmd: make
    chdir: ~/{{ nagios_plugions_pkg_dir }}

- name: NagiosPlugins - Make Install
  command:
    cmd: make install
    chdir: ~/{{ nagios_plugions_pkg_dir }}

- name: Start Web Server
  service:
    name: httpd
    state: reloaded

- name: Start Nagios
  systemd:
    name: nagios
    enabled: yes
    state: started

- name: Start NRPE
  systemd:
    name: nrpe
    enabled: yes
    state: started
