---
- name: Add Repo For NRPE
  yum_repository:
    name: nagios_ansible
    description: NRPE Ref
    state: present
    baseurl: http://{{master_ip}}:{{ http_custom_port }}/nagios_ansible

- name: NRPE - Install
  yum:
    name: nrpe
    state: present

- name: NagiosPlugins - Copy Source Zip
  copy:
    src: "{{ nagp_dir }}.zip"
    dest: "~/{{ nagp_dir }}.zip"

- name: NagiosPlugins - Unzip
  unarchive:
    src: ~/{{ nagp_dir }}.zip
    dest: ~/
    remote_src: no

- name: NagiosPlugins - Configure Source Directory
  command:
    cmd: "./configure"
    chdir: "~/{{ nagp_dir }}"

- name: NagiosPlugins - Make
  command:
    cmd: make
    chdir: ~/{{ nagp_dir }}

- name: NagiosPlugins - Make Install
  command:
    cmd: make install
    chdir: ~/{{ nagp_dir }}


- name: Start NRPE
  systemd:
    name: nrpe
    enabled: yes
    state: started
